disabled_rules: # rule identifiers to exclude from running
 - identifier_name
 - force_cast
 - for_where
 - function_body_length
 - private_over_fileprivate
 - file_length
 - large_tuple
 - unused_optional_binding
opt_in_rules: # some rules are only opt-in
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
force_cast: warning # implicitly
force_try: warning # implicitly
identifier_name:
  severity: warning # explicitly
type_body_length:
  - 700 # warning
  - 1500 # error
line_length:
  warning: 200
  error: 600
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
cyclomatic_complexity:
  warning: 15
  ignores_case_statements: true

